name: novellia_pets
services:
  # PostgreSQL Service
  postgres_db:
    image: postgres:18.2
    container_name: postgres_db
    restart: always
    env_file:
      - ./apps/api/.env
    ports:
      - "5432:5432"